apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    app: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-feed
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
        - name: api-feed
          image: 'dcjgs/udagram-api-feed:v1.0'
          envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: aws-secret
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          ports:
          - containerPort: 8080
